---
- name: 'Baixa o arquivo de instalação do Wordpress'
  get_url:
    url: 'https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Descompacta o wordpress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: /var/www/
    remote_src: yes
  become: yes

- name: 'Copia o arquivo wp-config.php'
  copy:
    src: '{{ wp_installation_dir }}/wp-config-sample.php'
    dest: '{{ wp_installation_dir }}/wp-config.php'
    remote_src: yes
  become: yes

- name: 'Configura o wp-config com as entradas do banco de dados'     
  replace:
    path: '{{ wp_installation_dir }}/wp-config.php'
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}"}
    - { regex: 'username_here', value: "{{ wp_username }}"}
    - { regex: 'password_here', value: '{{ wp_user_password }}'}
  become: yes